//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabVIDMAutomationService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ProfessionalServices : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProfessionalServices defaultInstance = ((ProfessionalServices)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProfessionalServices())));
        
        public static ProfessionalServices Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=127.0.0.1;Database=workshops;User=sa;Password=P@ssw0rd;")]
        public string DB_CONNECTION_STRING_WORKSHOP {
            get {
                return ((string)(this["DB_CONNECTION_STRING_WORKSHOP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://airwatch.vmwareidentity.com/")]
        public string VIDM_API_BASE_URL {
            get {
                return ((string)(this["VIDM_API_BASE_URL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AirWatchSEOnboarding")]
        public string VIDM_OAUTH_USERNAME {
            get {
                return ((string)(this["VIDM_OAUTH_USERNAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pW31vtl3xt3jchYlhyi83CMG1XmdNC2tWR4R2WdcHfOTPDHW")]
        public string VIDM_OAUTH_PASSWORD {
            get {
                return ((string)(this["VIDM_OAUTH_PASSWORD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("us8ex01.us8.airwlab.com")]
        public string SMTP_SERVER_HOSTNAME {
            get {
                return ((string)(this["SMTP_SERVER_HOSTNAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int SMTP_SERVER_PORT {
            get {
                return ((int)(this["SMTP_SERVER_PORT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jsheets@us8.airwlab.com")]
        public string SMTP_SERVICE_ACCT_EMAIL {
            get {
                return ((string)(this["SMTP_SERVICE_ACCT_EMAIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P@ssw0rd")]
        public string SMTP_SERVICE_ACCT_PASSWORD {
            get {
                return ((string)(this["SMTP_SERVICE_ACCT_PASSWORD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Workshop Administrator")]
        public string SMTP_SERVICE_ACCT_DISPLAY_NAME {
            get {
                return ((string)(this["SMTP_SERVICE_ACCT_DISPLAY_NAME"]));
            }
        }
    }
}
